---
- name: "ansible_stream8 | epel release: Install a list of packages"
  dnf:
    name:
      - epel-release
    state: present
  notify:
    - update dnf

- name: "ansible_stream8 | epel release: dnf check-updates"
  dnf:
    list: updates
    update_cache: true

- name: "ansible_stream8 | epel release: dnf security update"
  dnf:
    name: "*"
    security: yes
    state: latest
    exclude: kernel*
