---

- name: "ansible_stream8 | golang: check for pre-existing go"
  stat:
    path: "/usr/local/go/bin/go"
  register: gopath

- name: "ansible_stream8 | golang: current version found, proceed"
  block:
    - name: "ansible_stream8 | golang: set fact go version"
      command: "/usr/local/go/bin/go version"
      register: current_go_release_package
      changed_when: true

    - name: "ansible_stream8 | golang: decide whether to perform new install"
      set_fact:
        new_go_install: true
      when:
        - "golang_var not in current_go_release_package.stdout"
  when: gopath.stat.exists is true

- name: "ansible_stream8 | golang: no version found, set for new install"
  set_fact:
    new_go_install: true
  when: gopath.stat.exists is false

- name: "ansible_stream8 | golang: perform golang installation"
  block:
    - name: "ansible_stream8 | golang: collect golang and extract"
      get_url:
        url: "https://dl.google.com/go/go{{ golang_var }}.linux-amd64.tar.gz"
        dest: "/usr/src/go{{ golang_var }}.linux-amd64.tar.gz"

    - name: "ansible_stream8 | golang: unarchive collected golang package"
      unarchive:
        src: "/usr/src/go{{ golang_var }}.linux-amd64.tar.gz"
        dest: /usr/local
        remote_src: yes
        mode: '0755'

    - name: "ansible_stream8 | golang: add env path to profile"
      lineinfile:
        path: "/etc/profile"
        line: "export PATH=$PATH:/usr/local/go/bin"

    - name: "ansible_stream8 | golang: add gopath path to profile"
      lineinfile:
        path: "/etc/profile"
        line: "export GOPATH=/opt/go"

    - name: "ansible_stream8 | golang: cleanup source files"
      file:
        path: "/usr/src/go{{ golang_var }}.linux-amd64.tar.gz"
        state: absent

    - name: "ansible_stream8 | golang: create go/src path"
      file:
        path: "/opt/go/src"
        owner: "{{ dev_user }}"
        group: "{{ dev_user }}"
        mode: '0755'
        state: directory

    - name: "ansible_stream8 | golang: create go/lib path"
      file:
        path: "/opt/go/lib"
        owner: "{{ dev_user }}"
        group: "{{ dev_user }}"
        mode: '0755'
        state: directory

    - name: "ansible_stream8 | golang: create go/bin path"
      file:
        path: "/opt/go/bin"
        owner: "{{ dev_user }}"
        group: "{{ dev_user }}"
        mode: '0755'
        state: directory
  when:
    - new_go_install is true
